#####################################生产版配置###########################
server:
  port: 8080
spring:
  #生产版配置
  profiles: pro
  #配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/template?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  #指定使用redis数据库
  redis:
    port: 6379
    #password: 123456
    #连接超时时间
    timeout: 10000ms
  servlet:
    multipart:
      #设置单个文件上传最大限制
      max-file-size: 5MB
      #设置多个文件上传最大限制
      max-request-size: 100MB
mybatis:
  #设置MyBatis全局变量
  configuration-properties:
    #文件存放域名前缀
    filePathPrefix: http://192.168.3.233:8080/
#是否启用swagger
swagger:
  enable: false

#自定义全局变量*******注意:  :后面要有空格
global:
  #图片存放路径--项目打包后的jar包同级目录static
  base-file-path: /home/template/build/static/
  #允许跨域地址---多个地址用,(逗号)分隔开
  cors-filter-origins: http://localhost:8088,http://localhost:8088