#############################################通用配置#############################################
spring:
  #启动什么配置
  profiles:
    active: dev
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  #指定使用redis数据库
  redis:
    #索引(默认为0)
    database: 0
    host: 127.0.0.1
  jackson:
    #配置时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: classpath:static/,classpath:public/,file:static/
mybatis:
  #设置MyBatis配置
  configuration:
    #返回类型为Map时，null也返回
    call-setters-on-nulls: true
    #开启驼峰命名
    map-underscore-to-camel-case: true
  #指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  #为了使用输入页数为负或者超出最大页时候使页数为最小或最大值
  reasonable: false
  support-methods-arguments: true
  params: count=countSql