#############################################通用配置#############################################
spring:
  #启动什么配置
  profiles:
    active: dev
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  redis:
    #索引(默认为0)
    database: 0
    host: 127.0.0.1
    port: 6379
    #password: 123456
    #连接超时时间
    timeout: 10000ms
  servlet:
    multipart:
      #设置单个文件上传最大限制
      max-file-size: 5MB
      #设置多个文件上传最大限制
      max-request-size: 100MB
  jackson:
    #配置时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: classpath:static/,file:static/
mybatis:
  #设置MyBatis配置
  configuration:
    #返回类型为Map时，null也返回
    call-setters-on-nulls: true
    #开启驼峰命名
    map-underscore-to-camel-case: true
  #指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  #所在包配置别名
  type-aliases-package: com.weiziplus.springboot.common.models
#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  #为了使用输入页数为负或者超出最大页时候使页数为最小或最大值
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#日志打印
logging:
  config: classpath:config/logback-spring.xml

#自定义全局变量*******注意:  :后面要有空格
global:
  token:
    #系统用户token过期时间,单位秒
    admin-expire-time: 43200
    #web用户token过期时间,单位秒
    web-expire-time: 259200
  #10秒内超过多少次请求，暂时封ip
  ip-filter-max-num: 100