#####################################生产版配置###########################
server:
  port: 8080
  servlet:
    #添加请求前缀
    context-path: /github
spring:
  #生产版配置
  profiles: pro
  #配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/template?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  #redis
  redis:
    #索引(默认为0)
    database: 0
mybatis:
  #设置MyBatis全局变量
  configuration-properties:
    # 文件存放域名前缀
    filePathPrefix: http://39.96.52.201/github
#禁用swagger,
knife4j:
  production: true

#自定义全局变量*******注意:  :后面要有空格
global:
  #图片存放路径--项目打包后的jar包同级目录static
  base-file-path: /home/template/build/static
  #允许跨域地址(访问的浏览器的Origin,不设置默认*)---多个地址用,(英文逗号)分隔开---可精确到端口号
  cors-filter-origins: http://localhost,https://xxx.xxx.xxx
  #是否將异常详情展示给前端
  response-show-runtime-exception: false